name: todo_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you're publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/todoapp.png.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: assets/todoapp.png.jpg
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/
